/**
 * cPanel deployment packager — produces `pizza-day-night-deploy.zip`.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * NOT IN USE. The site is deployed on Vercel, which builds from the repository
 * and needs none of this. Kept, working, for a move back to shared hosting:
 *
 *     npm run cpanel:pack        build, then package
 *     npm run cpanel:pack:fast   package the build that is already there
 *
 * Before using it again, note that the database moved to PostgreSQL on
 * Supabase: the checks below still name `mariadb`, and `prisma/pizza_day_night.sql`
 * is a MySQL dump. Both would need regenerating. See DEPLOY.md.
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * A shared cPanel host cannot run `npm install` (its npm is broken and the
 * account's process limit is low), so nothing is built on the server: this
 * assembles the standalone build, the static files, and the one native package
 * the app needs in its Linux form, then zips the lot. On cPanel it is upload →
 * Extract → Restart, and nothing else, ever.
 *
 * Two things this project does NOT need, which older guides insist on:
 *
 *   - **No Prisma query engine.** Prisma 7 talks to the database through a
 *     driver adapter, which is plain JavaScript. There is no `.so.node` to ship
 *     and no `binaryTargets` to set.
 *   - **No `bcrypt` rebuild.** The project uses `bcryptjs`, also plain
 *     JavaScript.
 *
 * `sharp` is the single exception — see step 4.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const APP_NAME = "pizza-day-night";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const STANDALONE = path.join(ROOT, ".next", "standalone");
const STAGING = path.join(ROOT, "deploy-package");
const ZIP = path.join(ROOT, `${APP_NAME}-deploy.zip`);
const SHARP_CACHE = path.join(ROOT, "scripts", ".sharp-linux");

const log = (m) => console.log(`[deploy-pack] ${m}`);
const fail = (m) => {
  console.error(`\n[deploy-pack] ✖ ${m}\n`);
  process.exit(1);
};

// ---------- 0) Preconditions ----------
if (!fs.existsSync(STANDALONE)) {
  fail("No .next/standalone — run `npm run build` first (is output: 'standalone' set?).");
}

const generatedServerPath = path.join(STANDALONE, "server.js");
if (!fs.existsSync(generatedServerPath)) fail(".next/standalone/server.js is missing.");

// ---------- 1) Staging directory ----------
fs.rmSync(STAGING, { recursive: true, force: true });
fs.rmSync(ZIP, { force: true });
fs.mkdirSync(STAGING, { recursive: true });

log("Copying .next/standalone …");
fs.cpSync(STANDALONE, STAGING, { recursive: true });

// Tracing can pull in files that have no business on the server. `.env*` is the
// dangerous one: those are development secrets, and cPanel supplies the real
// values as environment variables instead.
for (const junk of [
  ".env",
  ".env.local",
  ".env.development",
  ".env.production",
  "scripts",
  "agent",
  "deploy-package",
  `${APP_NAME}-deploy.zip`,
]) {
  fs.rmSync(path.join(STAGING, junk), { recursive: true, force: true });
}

// ---------- 2) A server.js Passenger can start ----------
// Passenger decides an app is alive when it calls `listen()`, and it will not
// wait for Next to finish booting first. The generated server awaits `prepare()`
// before listening, which times out on this host — so the config Next serialised
// into it is lifted out and re-used in a server that listens immediately and
// prepares in the background.
const generatedServer = fs.readFileSync(generatedServerPath, "utf8");
const configMatch = generatedServer.match(/^const nextConfig = (.+)$/m);

if (!configMatch) {
  fail("Could not read nextConfig out of the generated server.js — did Next change its template?");
}

const passengerServer = `// Generated by scripts/package-deploy.mjs — do not edit by hand.
// Passenger detects the app through the immediate listen() below; Next is
// prepared in the background and any boot error is shown in the browser.
var http = require('http');

process.chdir(__dirname);
process.env.NODE_ENV = 'production';

var nextConfig = ${configMatch[1]}
process.env.__NEXT_PRIVATE_STANDALONE_CONFIG = JSON.stringify(nextConfig);

var next = require('next');
var app = next({ dev: false, dir: __dirname });
var handle = app.getRequestHandler();
var prepared = app.prepare();

var server = http.createServer(function (req, res) {
  prepared
    .then(function () { handle(req, res); })
    .catch(function (err) {
      console.error(err);
      res.writeHead(500, { 'Content-Type': 'text/plain; charset=utf-8' });
      res.end('فشل تشغيل الموقع:\\n\\n' + (err && err.message ? err.message : String(err)));
    });
});

// No fixed port: Passenger hands one over in PORT.
server.listen(process.env.PORT);
`;

fs.writeFileSync(path.join(STAGING, "server.js"), passengerServer);
log("Wrote the Passenger-compatible server.js.");

// ---------- 3) Static files ----------
// The minimal server serves these itself, but does not copy them.
log("Copying .next/static and public …");
fs.cpSync(path.join(ROOT, ".next", "static"), path.join(STAGING, ".next", "static"), {
  recursive: true,
});

const publicDir = path.join(ROOT, "public");
fs.cpSync(publicDir, path.join(STAGING, "public"), {
  recursive: true,
  filter: (src) => {
    const rel = path.relative(publicDir, src);
    // Keep the uploads folder, drop what is in it: those images belong to the
    // restaurant and live on the server. Shipping the local ones would
    // overwrite the real menu photos on every deploy.
    if (rel.startsWith("uploads") && rel !== "uploads" && !rel.endsWith(".gitkeep")) {
      return false;
    }
    return true;
  },
});

// ---------- 4) sharp, in its Linux form ----------
// `next/image` optimises the menu photos with sharp, which is a native module:
// the copy installed here is built for Windows and cannot run on the host. npm
// can fetch the Linux build from a Windows machine when told exactly which
// platform to resolve for, so it is downloaded once and cached.
const nextPkg = JSON.parse(
  fs.readFileSync(path.join(ROOT, "node_modules", "next", "package.json"), "utf8"),
);
const sharpSpec = nextPkg.optionalDependencies?.sharp;

if (!sharpSpec) fail("Could not read the sharp version out of the next package.");

const sharpMarker = path.join(SHARP_CACHE, ".spec");
const cacheValid =
  fs.existsSync(path.join(SHARP_CACHE, "node_modules", "@img", "sharp-linux-x64")) &&
  fs.existsSync(sharpMarker) &&
  fs.readFileSync(sharpMarker, "utf8") === sharpSpec;

if (!cacheValid) {
  log(`Downloading sharp@${sharpSpec} for linux-x64 (one time) …`);
  fs.rmSync(SHARP_CACHE, { recursive: true, force: true });
  fs.mkdirSync(SHARP_CACHE, { recursive: true });

  const npmArgs = [
    "install",
    `sharp@${sharpSpec}`,
    "--prefix",
    SHARP_CACHE,
    "--os=linux",
    "--cpu=x64",
    "--libc=glibc",
    "--no-save",
    "--no-audit",
    "--no-fund",
    "--ignore-scripts",
    "--loglevel=error",
  ];

  // Call npm's own entry point when it can be found next to this Node: spawning
  // `npm` through a shell on Windows is what breaks on paths with spaces.
  const npmCli = path.join(path.dirname(process.execPath), "node_modules", "npm", "bin", "npm-cli.js");
  const res = fs.existsSync(npmCli)
    ? spawnSync(process.execPath, [npmCli, ...npmArgs], { stdio: "inherit" })
    : spawnSync("npm", npmArgs, { stdio: "inherit", shell: process.platform === "win32" });

  if (res.status !== 0) fail("Downloading the Linux sharp failed — is the internet reachable?");
  fs.writeFileSync(sharpMarker, sharpSpec);
}

log("Merging the Linux sharp into the package …");
const cacheNM = path.join(SHARP_CACHE, "node_modules");
const stagingNM = path.join(STAGING, "node_modules");

fs.rmSync(path.join(stagingNM, "sharp"), { recursive: true, force: true });
fs.cpSync(path.join(cacheNM, "sharp"), path.join(stagingNM, "sharp"), { recursive: true });

// sharp's own small dependencies are nested inside it rather than hoisted, so
// they cannot collide with anything the traced build already put at the root.
for (const dep of fs
  .readdirSync(cacheNM)
  .filter((d) => d !== "sharp" && d !== "@img" && d !== ".bin" && d !== ".package-lock.json")) {
  fs.cpSync(path.join(cacheNM, dep), path.join(stagingNM, "sharp", "node_modules", dep), {
    recursive: true,
  });
}

for (const img of fs.readdirSync(path.join(cacheNM, "@img"))) {
  fs.cpSync(path.join(cacheNM, "@img", img), path.join(stagingNM, "@img", img), {
    recursive: true,
  });
}

// ---------- 5) Repair packages the trace only stubbed ----------
// A package named in `serverExternalPackages` is deliberately not bundled, and
// the tracer then records only its package.json — the code itself never gets
// copied. The site boots and dies on the first query with "Cannot find module
// .../lib/index.js", which on the server looks like a database fault.
//
// Rather than maintain a list of the affected packages (mariadb pulls
// iconv-lite, lru-cache and more, and that closure changes with every upgrade),
// find every directory that arrived as a bare manifest and copy the real one.
function findStubbedPackages(dir, prefix = "") {
  const stubs = [];

  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;

    const full = path.join(dir, entry.name);

    // Scoped packages hold their real packages one level down.
    if (entry.name.startsWith("@")) {
      stubs.push(...findStubbedPackages(full, `${entry.name}/`));
      continue;
    }

    const contents = fs.readdirSync(full);
    if (contents.length === 1 && contents[0] === "package.json") {
      stubs.push(prefix + entry.name);
    }
  }

  return stubs;
}

const stubbed = findStubbedPackages(stagingNM);

for (const name of stubbed) {
  const source = path.join(ROOT, "node_modules", name);

  if (!fs.existsSync(source)) {
    fail(`${name} is a stub in the package and missing from node_modules — run npm install.`);
  }

  fs.rmSync(path.join(stagingNM, name), { recursive: true, force: true });
  fs.cpSync(source, path.join(stagingNM, name), { recursive: true });
}

if (stubbed.length > 0) {
  log(`Restored ${stubbed.length} stubbed package(s): ${stubbed.join(", ")}`);
}

// ---------- 6) Defensive cleanup ----------
// SWC compiles the app during the build and is useless afterwards; left in, it
// is tens of megabytes of Windows binaries in a package bound for Linux.
const nextScoped = path.join(stagingNM, "@next");
if (fs.existsSync(nextScoped)) {
  for (const d of fs.readdirSync(nextScoped)) {
    if (d.startsWith("swc-")) {
      fs.rmSync(path.join(nextScoped, d), { recursive: true, force: true });
    }
  }
}

// ---------- 7) Safety checks — a failure here beats a broken site ----------
// Nothing may still be a bare manifest: step 5 either restored it or stopped.
const remainingStubs = findStubbedPackages(stagingNM);
if (remainingStubs.length > 0) {
  fail(`These packages are still empty shells: ${remainingStubs.join(", ")}`);
}

for (const [rel, label] of [
  ["server.js", "the startup file"],
  [".next/BUILD_ID", "the build id"],
  [".next/static", "the client assets"],
  ["node_modules/next/package.json", "the next package"],
  ["node_modules/@prisma/adapter-pg", "the Prisma PostgreSQL adapter"],
  ["node_modules/pg", "the pg driver"],
  ["node_modules/@img/sharp-linux-x64", "sharp for Linux"],
  ["public", "the public folder"],
  ["package.json", "package.json"],
]) {
  if (!fs.existsSync(path.join(STAGING, rel))) {
    fail(`Safety check: ${label} (${rel}) is missing from the package.`);
  }
}

for (const secret of [".env", ".env.local", ".env.production"]) {
  if (fs.existsSync(path.join(STAGING, secret))) fail(`${secret} leaked into the package!`);
}

// The agent holds PRINT_AGENT_TOKEN in its config and belongs on the
// restaurant's PC; finding it here means the tracing excludes stopped working.
if (fs.existsSync(path.join(STAGING, "agent"))) {
  fail("The print agent leaked into the package — it belongs on the restaurant's PC only.");
}

// sharp for Windows would be dead weight the Linux host cannot load.
const winSharp = path.join(stagingNM, "@img", "sharp-win32-x64");
if (fs.existsSync(winSharp)) {
  fs.rmSync(winSharp, { recursive: true, force: true });
  log("Removed the Windows sharp binary.");
}

// ---------- 8) Zip ----------
log("Zipping …");
let zipped = false;

/**
 * A real zip starts with `PK\x03\x04`.
 *
 * Worth checking, because the failure it catches is silent and expensive: the
 * `tar` on PATH may be GNU tar (Git Bash ships one) rather than the bsdtar
 * Windows provides, and GNU tar cannot write zip — it happily produces a *tar*
 * archive under the .zip name and exits 0. cPanel's Extract then fails on the
 * server, long after the upload.
 */
function isRealZip(file) {
  if (!fs.existsSync(file)) return false;

  const magic = Buffer.alloc(4);
  const fd = fs.openSync(file, "r");
  try {
    fs.readSync(fd, magic, 0, 4, 0);
  } finally {
    fs.closeSync(fd);
  }

  return magic[0] === 0x50 && magic[1] === 0x4b;
}

// Paths are relative to ROOT rather than absolute: GNU tar reads the colon in
// `C:\…` as a remote host and fails with "Cannot connect to C".
spawnSync("tar", ["-a", "-c", "-f", path.basename(ZIP), "-C", path.relative(ROOT, STAGING), "."], {
  stdio: ["ignore", "inherit", "pipe"],
  cwd: ROOT,
});

zipped = isRealZip(ZIP);

if (!zipped) {
  fs.rmSync(ZIP, { force: true });
  log("tar could not write a zip here — using Compress-Archive instead.");
}

if (!zipped) {
  const psRes = spawnSync(
    "powershell.exe",
    [
      "-NoProfile",
      "-Command",
      `Compress-Archive -Path '${STAGING}\\*' -DestinationPath '${ZIP}' -Force`,
    ],
    { stdio: "inherit" },
  );
  zipped = psRes.status === 0 && isRealZip(ZIP);
}

if (!zipped) fail("Could not create the zip.");

const mb = (n) => `${(n / 1024 / 1024).toFixed(1)}MB`;

console.log(`\n[deploy-pack] ✔ Done — ${path.basename(ZIP)} (${mb(fs.statSync(ZIP).size)})`);
console.log("cPanel: upload → Extract → Restart. Do NOT press Run NPM Install.\n");
